version: '3.6'
services:
  postgres:
    image: camptocamp/postgres:9.6
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - PGDATA=/var/lib/postgresql/data/pgdata
  sut:
    build:
      context: .
    command: 'sh integration-tests.sh'
    depends_on:
      - postgres
    environment:
      - PGPASSWORD=12345
      - S3_REGION=eu-west-2
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET=flowmoco-s3-backup-test
      - S3_PREFIX=postgres-test
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_EXTRA_OPTS=--schema=public -b
      - S3_FILENAME=postgres-backup-test
