version: '3.7'
services:
  postgres:
    image: camptocamp/postgres:9.6
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
  sut:
    build: .
    command: 'sh integration-tests.sh'
    depends_on:
      - postgres
